---
title: "PCA"
output: html_notebook
---

Let's explore the data using PCA


```{r}
library(tidyverse)
library(tictoc)
library(caret)
library(ggfortify)
library(MASS)
library(cluster)
source("./parameters.R")
```

# Open the data set

```{r}
# Open the bag of words
fileName = "bow_tfidf__min_words_100_2grams_1000__sampling_balanced__cor_cut_0.3_from_1408_to_1110_rm0.csv"
df = read_csv(fileName, col_types=col_types_df)
df = df[,-c(2,3,5:9)]
# During tests, we can work on a sample
sampled = TRUE
if (sampled == TRUE) {
  set.seed(42)
  max = nrow(df)
  sampled = round(max/10)
  df = df[sample(max, sampled), ]
}
# show the data set
df
```

# Splitting the data

PCA is a clustering technique so we can get ride of the train/test split and the labels.

```{r}
X = df[,-c(1,2)]
X
```

# Run PCA

Build the PCA

```{r}
PCA_X = princomp(X)
#PCA_X
```

Show the resulting screenplot

```{r}
screeplot(PCA_X)
```
# Visualize the result

Project the data in the new space

```{r}
X_proj = predict(PCA_X)
```

Plot the data on the 2 first axis

```{r fig.width=20}
area = 0.1

autoplot(PCA_X, data = df, colour = 'df_toxic', abel = TRUE, shape = FALSE, label.size = 3, loadings = TRUE, loadings.label = TRUE, loadings.label.size = 5) +
  coord_cartesian(xlim=c(-area,area), ylim=c(-area,area))
```


